version: '3'
services:
  webapp:
    build: .
    expose:
      - "8080"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  nginx-proxy:
    image: nginx:1.13
    depends_on:
      - webapp
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d